# Generated by Django 3.1.3 on 2021-06-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
